# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-14 09:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Housing',
            fields=[
                ('zid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=128)),
                ('zipcode', models.IntegerField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('description', models.CharField(max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommender.UserProfile', verbose_name='user_housing')),
            ],
        ),
        migrations.CreateModel(
            name='RoommatePreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender_prefer', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('B', 'Both')], max_length=1)),
                ('smoke', models.BooleanField()),
                ('party', models.BooleanField()),
                ('sleep_late', models.BooleanField()),
                ('pet', models.BooleanField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
