# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-14 10:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0002_housing_roommatepreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommatepreference',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='recommender.UserProfile'),
        ),
    ]
