# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-09 00:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0004_auto_20180508_2352'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisLikeHousing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommender.Housing', verbose_name='housing_disliked')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommender.UserProfile', verbose_name='housing_dislike')),
            ],
        ),
        migrations.AlterField(
            model_name='likehousing',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommender.Housing', verbose_name='housing_liked'),
        ),
        migrations.AlterField(
            model_name='likehousing',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommender.UserProfile', verbose_name='housing_like'),
        ),
        migrations.AlterUniqueTogether(
            name='dislikehousing',
            unique_together=set([('user', 'house')]),
        ),
    ]
