# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-09 00:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0006_auto_20180509_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likehousing',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='housing_like'),
        ),
    ]
