# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-09 03:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recommender', '0007_auto_20180509_0042'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendRoomate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(default=False)),
                ('dislike', models.BooleanField(default=False)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user1', to=settings.AUTH_USER_MODEL, verbose_name='user1')),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user2', to=settings.AUTH_USER_MODEL, verbose_name='user2')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='recommendroomate',
            unique_together=set([('user1', 'user2')]),
        ),
    ]
