# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-10 03:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recommender', '0009_userprofile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendRoommate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField()),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user1', to=settings.AUTH_USER_MODEL, verbose_name='user1')),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user2', to=settings.AUTH_USER_MODEL, verbose_name='user2')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='recommendroomate',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='recommendroomate',
            name='user1',
        ),
        migrations.RemoveField(
            model_name='recommendroomate',
            name='user2',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, default='profile_images/profile_default.jpg', upload_to='profile_images'),
        ),
        migrations.DeleteModel(
            name='RecommendRoomate',
        ),
        migrations.AlterUniqueTogether(
            name='recommendroommate',
            unique_together=set([('user1', 'user2')]),
        ),
    ]
