# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-11 06:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0011_auto_20180510_0730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housing',
            name='description',
        ),
    ]
